Server:
  Host: localhost # for docker to use in mac put: 0.0.0.0
  Port: 8080

Redis:
  Host: localhost # for docker to use in mac put: host.docker.internal
  Port: 6379 # for docker use: 6380
  User:
  Pass:

Collector:
  Concurrent: true
  Interval: 30 # 0 means once at time, and 0 > means an interval in second
  SplitFactor: 30 # Be used in pagination to do collecting in concurrent


Credentials:
  UserName: i.jedari@gmail.com
  Password: 123456789

RateLimiter:
  Active: false
  Rate: 10 # per period
  Period: 1 # in minutes

OriginRemote:
  BaseURL: "https://vgang.io/api/vgang-core/v1"
  Products: "/retailers/products?search=shirt&sort=Latest&dont_show_out_of_stock=1"
  Login: "/auth/login/retailer/vgang"
